site_name: VM Operator
site_url: https://github.com/vmware-tanzu/vm-operator
repo_url: https://github.com/vmware-tanzu/vm-operator
edit_uri: blob/main/docs/
docs_dir: docs
site_dir: .site

theme:
  name: material
  custom_dir: docs/www/themes/material

  favicon: favicon.svg
  icon:
    logo: vm-op/logo-white-solid

  palette:
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

  features:
  - content.code.annotate
  - content.code.copy
  - content.tabs.link
  - navigation.tabs
  - navigation.top
  - navigation.sections
  - navigation.expand
  - navigation.tracking
  - navigation.footer
  - navigation.header
  - navigation.path
  - toc.follow
  
extra_css:
- www/css/vm-operator.css
- www/css/vm-operator-font.css

#extra:
  # TODO(akutz) Get this working with RTFD
  # version:
  #   default: latest
  #   provider: mike

markdown_extensions:
- admonition
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
    options:
      custom_icons:
      - material/.icons
- pymdownx.inlinehilite
- pymdownx.highlight:
    use_pygments: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.details
- tables
- attr_list
- md_in_html

nav:
- Home: index.md
- Getting started:
  - Platforms: start/platforms.md
  - Recommended images: start/images.md
  - Contributing: start/contributing.md
  - Release Notes: start/release-notes.md
  - License: start/license.md
- Concepts:
  - Workloads:
    - VirtualMachine: concepts/workloads/vm.md
    - VirtualMachineClass: concepts/workloads/vm-class.md
    - Guest Customization: concepts/workloads/guest.md
  - Images:
    - VirtualMachineImage: concepts/images/vm-image.md
    - Publish a VM Image: concepts/images/pub-vm-image.md
  - Services & Networking:
    - VirtualMachineService: concepts/services-networking/vm-service.md
    - Guest Network Config: concepts/services-networking/guest-net-config.md
- Tutorials:
  - Deploy VM:
    - With Cloud-Init: tutorials/deploy-vm/cloudinit.md
    - With vAppConfig: tutorials/deploy-vm/vappconfig.md
- Reference:
  - Developers:
    - Project Guidelines: ref/dev/project-guidelines.md
    - Build Reference: ref/dev/build-reference.md
    - Release Process: ref/dev/release-process.md
