---
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: system
spec:
  ports:
  - name: https
    port: 443
    targetPort: $(WEBHOOK_SERVICE_CONTAINER_PORT)
  selector:
    control-plane: controller-manager
