# permissions for certman cert secret access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certman-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
