# permissions to do edit contentsources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: contentsource-editor-role
rules:
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - contentsources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - contentsources/status
  verbs:
  - get
  - patch
  - update
