# permissions to do viewer contentlibraryproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: contentlibraryprovider-viewer-role
rules:
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - contentlibraryproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - contentlibraryproviders/status
  verbs:
  - get
