# permissions to do viewer virtualmachineimages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualmachineimage-viewer-role
rules:
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachineimages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachineimages/status
  verbs:
  - get
