# permissions to do viewer virtualmachineclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualmachineclass-viewer-role
rules:
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachineclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachineclasses/status
  verbs:
  - get
