# permissions to do viewer virtualmachinesetresourcepolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualmachinesetresourcepolicy-viewer-role
rules:
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachinesetresourcepolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachinesetresourcepolicies/status
  verbs:
  - get
