apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineClass
metadata:
  name: guaranteed-small
spec:
  hardware:
    cpus: 2
    memory: 4Gi
  policies:
    resources:
      requests:
        cpu: 2000m
        memory: 4Gi
