apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cnsnodevmattachments.cns.vmware.com
spec:
  group: cns.vmware.com
  names:
    kind: CnsNodeVmAttachment
    listKind: CnsNodeVmAttachmentList
    plural: cnsnodevmattachments
    singular: cnsnodevmattachment
  scope: Namespaced
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: CnsNodeVmAttachment is the Schema for the cnsnodevmattachments
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CnsNodeVmAttachmentSpec defines the desired state of CnsNodeVmAttachment
          type: object
        status:
          description: CnsNodeVmAttachmentStatus defines the observed state of CnsNodeVmAttachment
          type: object
      type: object